TIME	COSCS107S	COSCS128S	COSCS129S	COSCS130S	COSCS131S	COSCS132S	COSCS133S	
00716602088.87	            DISA	            INAC	             ACT	             ACT	            INAC	             INAC	             INAC
00716602121.67	            DISA	            INAC	             ACT	             ACT	            INAC	             INAC	             INAC
00716603860.07	            DISA	            INAC	             ACT	             ACT	            INAC	             INAC	             INAC
00716603892.87	            DISA	            INAC	             ACT	             ACT	            INAC	             INAC	             INAC
00716603925.67	            DISA	            INAC	             ACT	             ACT	            INAC	             INAC	             INAC
