TIME	COSCS107S	COSCS128S	COSCS129S	COSCS130S	COSCS131S	COSCS132S	COSCS133S	
00716602088.87	            INAC	            INAC	             ACT	             ACT	            INAC	             ACT	             ACT
00716602121.67	            INAC	            INAC	             ACT	             ACT	            INAC	             ACT	             ACT
00716603860.07	            INAC	            INAC	             ACT	             ACT	            INAC	             ACT	             ACT
00716603892.87	            INAC	            INAC	             ACT	             ACT	            INAC	             ACT	             ACT
00716603925.67	            INAC	            INAC	             ACT	             ACT	            INAC	             ACT	             ACT
